apiVersion: skaffold/v1beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: alexcmachado/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.css'
            dest: .
          - src: 'src/**/*.html'
            dest: .
    - image: alexcmachado/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: alexcmachado/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*